In [1]:
#!pip install mplcursors
!pip install bokeh
!pip install pyarrow

Requirement already satisfied: bokeh in c:\users\torsh\anaconda3\lib\site-packages (2.4.2)
Requirement already satisfied: packaging>=16.8 in c:\users\torsh\anaconda3\lib\site-packages (from bokeh) (21.3)
Requirement already satisfied: tornado>=5.1 in c:\users\torsh\anaconda3\lib\site-packages (from bokeh) (6.1)
Requirement already satisfied: PyYAML>=3.10 in c:\users\torsh\anaconda3\lib\site-packages (from bokeh) (6.0)
Requirement already satisfied: numpy>=1.11.3 in c:\users\torsh\anaconda3\lib\site-packages (from bokeh) (1.21.5)
Requirement already satisfied: pillow>=7.1.0 in c:\users\torsh\anaconda3\lib\site-packages (from bokeh) (9.0.1)
Requirement already satisfied: typing-extensions>=3.10.0 in c:\users\torsh\anaconda3\lib\site-packages (from bokeh) (4.1.1)
Requirement already satisfied: Jinja2>=2.9 in c:\users\torsh\anaconda3\lib\site-packages (from bokeh) (2.11.3)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\torsh\anaconda3\lib\site-packages (from Jinja2>=2.9->bokeh) (2.0.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\torsh\anaconda3\lib\site-packages (from packaging>=16.8->bokeh) (3.0.4)

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pyarrow in c:\users\torsh\anaconda3\lib\site-packages (11.0.0)
Requirement already satisfied: numpy>=1.16.6 in c:\users\torsh\anaconda3\lib\site-packages (from pyarrow) (1.21.5)

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import os
import umap
import pickle
import pandas as pd
import matplotlib.pyplot as plt
from bokeh.palettes import plasma
from bokeh.plotting import figure
from bokeh.transform import transform
from bokeh.io import output_file, show, save
from bokeh.models import ColumnDataSource, HoverTool, LinearColorMapper, WheelZoomTool, ColorBar

## Initial Training with Astronomaly

In [21]:
ml_score_1 = pd.read_csv(f"C:/Users/torsh/git/TESS/SVM/astronomaly/score_/ml_scores_1.csv")
ml_score_1.rename(columns = {'Unnamed: 0':'index'}, inplace = True)
ml_score_1.head()

,index,score,human_label,predicted_user_score,trained_score
0,99_36146911-Kilonova,4.804071,5,1.89,4.803813
1,67_2836309-SNIa-91bg,4.800778,1,1.51,4.800778
2,67_1191548-SNIa-91bg,4.796162,1,1.79,4.796162
3,Ib_6942404-SNIb,4.793235,0,1.22,4.793214
4,62_855740-ILOT,4.790390,5,2.01,4.790390

In [22]:
umap_data = pd.read_parquet(f"C:/Users/torsh/git/TESS/SVM/astronomaly/score_/UMAP_Plot_output.parquet", engine="pyarrow")
umap_data.rename(columns = {'0':'feature_1', '1':'feature_2'}, inplace = True)
umap_data = umap_data.reset_index()
umap_data.head()

                index  feature_1  feature_2
0   90_74715086-uLens  17.619793   4.314851
1  90_128043216-uLens   2.073710   1.619488
2   90_64641100-uLens   3.687694   9.670859
3  90_127948462-uLens   6.018578   2.415306
4   90_94999591-uLens  18.192907   3.372912

In [23]:
new_data_df = pd.merge(ml_score_1,umap_data, on="index", how="inner") 
new_data_df.head(10)

,index,score,human_label,predicted_user_score,trained_score,feature_1,feature_2
0,99_36146911-Kilonova,4.804071,5,1.89,4.803813,6.059938,8.548410
1,67_2836309-SNIa-91bg,4.800778,1,1.51,4.800778,19.260895,1.507748
2,67_1191548-SNIa-91bg,4.796162,1,1.79,4.796162,3.353399,4.099684
3,Ib_6942404-SNIb,4.793235,0,1.22,4.793214,-0.317065,3.594306
4,62_855740-ILOT,4.790390,5,2.01,4.790390,18.858736,1.687921
5,IIb_4102837-SNIIb,4.781346,0,3.72,4.781302,5.744840,-2.171738
6,63_86054256-CART,4.775782,0,0.40,4.775776,3.226532,1.304134
7,90_25227748-SNIa,4.764926,0,1.20,4.764926,0.282431,3.791597
8,IIn_33713796-SNIIn,4.761254,0,3.72,4.761254,18.507267,2.862624
9,62_1346979-ILOT,4.758646,5,1.91,4.758304,17.898989,3.101525

In [24]:
source = ColumnDataSource(data=dict(x=new_data_df["feature_1"], y=new_data_df["feature_2"], desc=new_data_df["index"], score=new_data_df["score"]))
hover = HoverTool(tooltips=[
        ('Label:', '@desc'),
        ('Score:', '@score'),
        ])
mapper = LinearColorMapper(palette=plasma(256), low=min(new_data_df["score"]), high=max(new_data_df["score"]))
p = figure(plot_width=1000, plot_height=800, tools=[hover, WheelZoomTool()], title=f"Cluster_-1 using Astronomaly (retraining with ~200 samples)", toolbar_location = "below")
p.circle("x", "y",size=10, source=source, line_color=None, fill_color={"field":"score","transform":mapper})
bar = ColorBar(color_mapper=mapper, location=(0,0))
p.add_layout(bar, "left")
output_file(f"C:/Users/torsh/git/TESS/SVM/astronomaly/cluster_-1_train1.html")
save(p)
#show(p)

'C:\\Users\\torsh\\git\\TESS\\SVM\\astronomaly\\cluster_-1_train1.html'

## Retraining with Astronomaly using 200 samples

In [25]:
ml_score_2 = pd.read_csv(f"C:/Users/torsh/git/TESS/SVM/astronomaly/score_/ml_scores_4.csv")
ml_score_2.rename(columns = {'Unnamed: 0':'index'}, inplace = True)
ml_score_2.head()

,index,score,human_label,predicted_user_score,trained_score
0,Ic-BL_9113982-SNIc-BL,2.701176,1,1.19,2.677778
1,II_5249538-SNII,2.696192,1,1.45,2.694536
2,62_110541037-ILOT,2.682773,5,1.65,2.544501
3,Ic-BL_12525843-SNIc-BL,2.681918,1,1.18,2.681906
4,62_68485967-ILOT,2.680154,5,1.21,2.679874

In [26]:
umap_data = pd.read_parquet(f"C:/Users/torsh/git/TESS/SVM/astronomaly/score_/UMAP_Plot_output.parquet", engine="pyarrow")
umap_data.rename(columns = {'0':'feature_1', '1':'feature_2'}, inplace = True)
umap_data = umap_data.reset_index()
umap_data.head()

                index  feature_1  feature_2
0   90_74715086-uLens  17.619793   4.314851
1  90_128043216-uLens   2.073710   1.619488
2   90_64641100-uLens   3.687694   9.670859
3  90_127948462-uLens   6.018578   2.415306
4   90_94999591-uLens  18.192907   3.372912

In [27]:
new_data_df = pd.merge(ml_score_2,umap_data, on="index", how="inner") 
new_data_df.head(10)

,index,score,human_label,predicted_user_score,trained_score,feature_1,feature_2
0,Ic-BL_9113982-SNIc-BL,2.701176,1,1.19,2.677778,4.625932,0.534421
1,II_5249538-SNII,2.696192,1,1.45,2.694536,6.353080,3.795506
2,62_110541037-ILOT,2.682773,5,1.65,2.544501,5.434579,0.785668
3,Ic-BL_12525843-SNIc-BL,2.681918,1,1.18,2.681906,14.433760,2.693869
4,62_68485967-ILOT,2.680154,5,1.21,2.679874,5.579071,-0.984776
5,IIb_6866036-SNIIb,2.670850,1,1.26,2.670849,6.516045,7.984044
6,II_29626546-SNII,2.669594,1,1.21,2.669539,6.669990,6.958165
7,Ib_27931308-SNIb,2.668617,1,1.38,2.668600,5.780562,1.747330
8,II_34641447-SNII,2.665749,1,4.64,2.665735,-0.312717,3.405697
9,52_2681318-SNIa-x,2.662123,1,1.21,2.661595,18.504045,2.890711

In [28]:
source = ColumnDataSource(data=dict(x=new_data_df["feature_1"], y=new_data_df["feature_2"], desc=new_data_df["index"], score=new_data_df["trained_score"]))
hover = HoverTool(tooltips=[
        ('Label:', '@desc'),
        ('Score:', '@score'),
        ])
mapper = LinearColorMapper(palette=plasma(256), low=min(new_data_df["score"]), high=max(new_data_df["score"]))
p = figure(plot_width=1000, plot_height=800, tools=[hover, WheelZoomTool()], title=f"Cluster_-1 using Astronomaly (retraining with ~500 samples)", toolbar_location = "below")
p.circle("x", "y",size=10, source=source, line_color=None, fill_color={"field":"score","transform":mapper})
bar = ColorBar(color_mapper=mapper, location=(0,0))
p.add_layout(bar, "left")
output_file(f"C:/Users/torsh/git/TESS/SVM/astronomaly/cluster_-1_train4.html")
save(p)
#show(p)

'C:\\Users\\torsh\\git\\TESS\\SVM\\astronomaly\\cluster_-1_train4.html'